import datetime
from pathlib import Path
from typing import cast

import tomllib

from data_farm.cli.base import AppContext, InspectNamespace
from data_farm.emitters.sql import ColumnEmitDefinition, SqlEmitter
from data_farm.planners.context import PatternRegistry, PlanContext
from data_farm.planners.registry import PlannerRegistry
from data_farm.schema.protocols import RelationalInspector
from data_farm.schema.registry import create_inspector
from data_farm.suggestors.defaults import build_default_registry
from data_farm.suggestors.engine import suggest_for_column
from data_farm.utils.config import load_data_source_config


def handle_inspect(ctx: AppContext, ns: InspectNamespace):
    """Process a data source inspection request."""
    projects_root = ctx.projects_root
    rows_per_table = int(ns.rows) or int(ctx.max_generation)
    project_path = ns.project
    config_path = ns.config
    pp = Path(project_path)
    ppp = Path(ctx.data_dir) / "projects" / pp if len(pp.parts) == 1 else pp

    acp = Path(ctx.config_dir) / "datafarm.toml"
    with acp.open("rb") as f:
        ac = tomllib.load(f)

    psd = ac["project"]["projects_root"]
    pd = Path(psd) / pp if len(pp.parts) == 1 else pp
    config = load_data_source_config(str(Path(pd) / "data_source_config.toml"))
    rng = ctx.rng
    with create_inspector(config[0]) as insp:
        db = cast(RelationalInspector, insp)
        insp_res = db.inspect_all_tables()
        reg = build_default_registry()
        all_suggestors = reg.all()
        e = SqlEmitter()
        preg = PlannerRegistry.default()
        patdir = pd / "patterns"
        patterns_dir = Path(patdir)
        pctx = PlanContext(rng=rng, patterns=PatternRegistry(patterns_dir), rows_per_table=rows_per_table)
        ed: list[ColumnEmitDefinition] = []
        for t in insp_res:
            for _ in range(pctx.rows_per_table):
                ed.clear()
                for c in t.columns:
                    s = suggest_for_column(c, all_suggestors)
                    planner = preg.get(s.strategy)
                    if not planner:
                        raise ValueError(
                            f"Planner could not be found for column {c.name} of type {c.data_type.name} in table {t.table} and strategy {s.strategy}."
                        )
                    maybe_def = planner.plan(c, s, pctx)
                    if maybe_def:
                        ed.append(maybe_def)

                if ns.output_file:
                    p = Path(ns.output_file)
                    with p.open("a+") as f:
                        f.write("-- Generated by dfarm\n")
                        f.write(f"-- Seed: {ctx.seed}\n")
                        f.write(f"-- Rows Per Table: {rows_per_table}\n")
                        f.write(f"-- Timestamp: {datetime.datetime.now()}\n")
                        f.write("\n")
                        for line in e.emit(t.table, ed):
                            f.write(line + "\n")
                else:
                    for line in e.emit(t.table, ed):
                        print(line)
