from __future__ import annotations

import datetime
from collections.abc import Iterable
from contextlib import nullcontext
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TextIO, cast

from data_farm.cli.base import AppContext, InspectNamespace
from data_farm.emitters.base import Emitter
from data_farm.emitters.sql import ColumnEmitDefinition, SqlEmitter
from data_farm.models.models import TableInspection
from data_farm.planners.context import PatternRegistry, PlanContext
from data_farm.planners.generation_plan import GenerationPlan
from data_farm.planners.registry import PlannerRegistry
from data_farm.schema.protocols import RelationalInspector
from data_farm.schema.registry import create_inspector
from data_farm.suggestors.base import PatternSuggestor
from data_farm.suggestors.defaults import build_default_registry
from data_farm.suggestors.engine import suggest_for_column
from data_farm.utils.config import load_data_source_config


def handle_inspect(app_ctx: AppContext, ns: InspectNamespace):
    """Process a data source inspection request."""
    insp_ctx = create_inspection_context(app_ctx, ns)
    insp_res = inspect(insp_ctx.data_source_config)

    gen_plans: dict[tuple[str, str], GenerationPlan] = get_generation_plans(insp_ctx, insp_res)

    out_path = Path(ns.output_file) if ns.output_file else None

    generate_data(out_path, app_ctx, insp_ctx, insp_res, gen_plans)


def make_file_header(seed: str | int | None, rows_per_table: str) -> str:
    generated_by = "-- Generated by dfarm"
    rng_seed = f"-- Seed: {seed}"
    rows_per_table = f"-- Rows Per Table: {rows_per_table}"
    timestamp = f"-- Timestamp: {datetime.datetime.now()}"

    return f"{generated_by}\n{rng_seed}\n{rows_per_table}\n{timestamp}\n\n"


@dataclass(frozen=True)
class InspectionContext:
    plan_context: PlanContext
    suggestors: list[PatternSuggestor]
    planner_registry: PlannerRegistry
    emitter: Emitter
    data_source_config: list[dict[str, Any]]
    rows_per_table: int


def create_inspection_context(app_ctx: AppContext, ns: InspectNamespace) -> InspectionContext:
    projects_root = app_ctx.projects_root
    rows_per_table = int(ns.rows) or int(app_ctx.max_generation)
    project_path = Path(ns.project)

    project_dir = projects_root / project_path if len(project_path.parts) == 1 else project_path
    ds_config = load_data_source_config(str(project_dir / "data_source_config.toml"))
    rng = app_ctx.rng

    suggestor_reg = build_default_registry()
    all_suggestors = suggestor_reg.all()

    sql_emitter = SqlEmitter()
    planner_reg = PlannerRegistry.default()

    patterns_dir = project_dir / "patterns"
    plan_ctx = PlanContext(rng=rng, patterns=PatternRegistry(patterns_dir), rows_per_table=rows_per_table)

    return InspectionContext(
        plan_context=plan_ctx,
        suggestors=all_suggestors,
        planner_registry=planner_reg,
        emitter=sql_emitter,
        data_source_config=ds_config,
        rows_per_table=rows_per_table,
    )


def inspect(data_source_config: list[dict[str, Any]]) -> list[TableInspection]:
    with create_inspector(data_source_config[0]) as insp:
        db = cast(RelationalInspector, insp)
        return db.inspect_all_tables()


def get_generation_plans(
    inspection_context: InspectionContext, inspection_results: list[TableInspection]
) -> dict[tuple[str, str], GenerationPlan]:
    gen_plans: dict[tuple[str, str], GenerationPlan] = {}

    for t in inspection_results:
        for c in t.columns:
            suggestion = suggest_for_column(c, inspection_context.suggestors)
            planner = inspection_context.planner_registry.get(suggestion.strategy)
            if planner is None:
                raise ValueError(
                    f"No planner for table {t.table} column={c.name} type={c.data_type.name} strategy={suggestion.strategy}."
                )
            gen_plans[t.table, c.name] = GenerationPlan(
                table=t.table,
                column=c.name,
                suggestion=suggestion,
                col_planner=planner,
            )

    return gen_plans


def _build_emit_defs(
    table: TableInspection,
    gen_plans: dict[tuple[str, str], GenerationPlan],
    plan_ctx: PlanContext,
) -> list[ColumnEmitDefinition]:
    ed: list[ColumnEmitDefinition] = []
    append = ed.append

    for c in table.columns:
        gen_plan = gen_plans[(table.table, c.name)]
        maybe_def = gen_plan.col_planner.plan(c, gen_plan.suggestion, plan_ctx)
        if maybe_def is not None:
            append(maybe_def)

    return ed


def _write_lines(lines: Iterable[str], out: TextIO | None) -> None:
    if out is None:
        for line in lines:
            print(line)
        return

    out.write("\n".join(lines))
    out.write("\n")


def generate_data(
    out_path: Path | None,
    app_ctx: AppContext,
    insp_ctx: InspectionContext,
    insp_res: list[TableInspection],
    gen_plans: dict[tuple[str, str], GenerationPlan],
) -> None:
    file_cm = out_path.open("w", buffering=1024 * 1024) if out_path is not None else nullcontext(None)

    with file_cm as out_handle:
        if out_handle is not None:
            out_handle.write(make_file_header(app_ctx.seed, str(insp_ctx.rows_per_table)))

        for t in insp_res:
            for _ in range(insp_ctx.plan_context.rows_per_table):
                ed = _build_emit_defs(t, gen_plans, insp_ctx.plan_context)
                lines = insp_ctx.emitter.emit(t.table, ed)
                _write_lines(lines, out_handle)
