from __future__ import annotations

import datetime
import logging
from collections.abc import Callable
from contextlib import nullcontext
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TextIO, cast

from data_farm.cli.base import AppContext, InspectNamespace
from data_farm.emitters.sql import format_values_fast, get_formatter
from data_farm.logging.logging import timed
from data_farm.models.models import TableInspection
from data_farm.planners.context import PatternRegistry, PlanContext
from data_farm.planners.generation_plan import GenerationPlan
from data_farm.planners.registry import PlannerRegistry
from data_farm.schema.protocols import RelationalInspector
from data_farm.schema.registry import create_inspector
from data_farm.suggestors.base import PatternSuggestor
from data_farm.suggestors.defaults import build_default_registry
from data_farm.suggestors.engine import suggest_for_column
from data_farm.utils.config import load_data_source_config
from data_farm.utils.enums import SqlType

logger = logging.getLogger("dfarm")


def handle_inspect(app_ctx: AppContext, ns: InspectNamespace) -> None:
    """Process a data source inspection request."""

    with timed(logger, "Building Inspection Context"):
        insp_ctx = create_inspection_context(app_ctx, ns)

    with timed(logger, "Inspecting"):
        insp_res = inspect(insp_ctx.data_source_config, insp_ctx.schema)

    with timed(logger, "Building data generation plans"):
        gen_plans: dict[tuple[str, str], GenerationPlan] = get_generation_plans(insp_ctx, insp_res)

    out_path = Path(ns.output_file) if ns.output_file else None

    with timed(logger, "Generating data"):
        generate_data(out_path, app_ctx, insp_ctx, insp_res, gen_plans)


def make_file_header(seed: str | int | None, rows_per_table: str) -> str:
    generated_by = "-- Generated by dfarm"
    rng_seed = f"-- Seed: {seed}"
    rows_per_table = f"-- Rows Per Table: {rows_per_table}"
    timestamp = f"-- Timestamp: {datetime.datetime.now()}"

    return f"{generated_by}\n{rng_seed}\n{rows_per_table}\n{timestamp}\n\n"


@dataclass(frozen=True)
class InspectionContext:
    plan_context: PlanContext
    suggestors: list[PatternSuggestor]
    planner_registry: PlannerRegistry
    data_source_config: list[dict[str, Any]]
    rows_per_table: int
    schema: str
    insert_batch_size: int


def create_inspection_context(app_ctx: AppContext, ns: InspectNamespace) -> InspectionContext:
    projects_root = app_ctx.projects_root
    rows_per_table = int(ns.rows) or int(app_ctx.max_generation)
    project_path = Path(ns.project)

    project_dir = projects_root / project_path if len(project_path.parts) == 1 else project_path
    ds_config = load_data_source_config(str(project_dir / "data_source_config.toml"))
    rng = app_ctx.rng

    suggestor_reg = build_default_registry()
    all_suggestors = suggestor_reg.all()

    planner_reg = PlannerRegistry.default()

    patterns_dir = project_dir / "patterns"
    plan_ctx = PlanContext(rng=rng, patterns=PatternRegistry(patterns_dir), rows_per_table=rows_per_table)

    schema = ns.schema

    batch_size = int(getattr(ns, "insert_batch_size", 1) or 1)
    batch_size = max(batch_size, 1)

    logger.debug("Inspection Context: projects_root=%s", projects_root)
    logger.debug("Inspection Context: project_dir=%s", project_dir)
    logger.debug("Inspection Context: patterns_dir=%s", patterns_dir)
    logger.debug("Inspection Context: rows_per_table=%d", rows_per_table)
    logger.debug("Inspection Context: batch_size=%d", batch_size)
    logger.debug("Inspection Context: schema=%s", schema)

    return InspectionContext(
        plan_context=plan_ctx,
        suggestors=all_suggestors,
        planner_registry=planner_reg,
        data_source_config=ds_config,
        rows_per_table=rows_per_table,
        schema=schema,
        insert_batch_size=batch_size,
    )


def inspect(data_source_config: list[dict[str, Any]], schema: str) -> list[TableInspection]:
    with create_inspector(data_source_config[0]) as insp:
        db = cast(RelationalInspector, insp)
        return db.inspect_all_tables(schema=schema)


def get_generation_plans(
    inspection_context: InspectionContext,
    inspection_results: list[TableInspection],
) -> dict[tuple[str, str], GenerationPlan]:
    gen_plans: dict[tuple[str, str], GenerationPlan] = {}

    for t in inspection_results:
        for c in t.columns:
            suggestion = suggest_for_column(c, inspection_context.suggestors)
            planner = inspection_context.planner_registry.get(suggestion.strategy)
            if planner is None:
                raise ValueError(
                    "No planner for table "
                    f"{t.table} column={c.name} type={c.data_type.name} "
                    f"strategy={suggestion.strategy}."
                )
            gen_plans[t.table, c.name] = GenerationPlan(
                table=t.table,
                column=c.name,
                suggestion=suggestion,
                col_planner=planner,
            )

    return gen_plans


@dataclass(frozen=True, slots=True)
class CompiledEmit:
    name: str
    data_type: SqlType
    value_fn: Callable[[], Any | None]
    formatter: Callable[[Any], str] | None


@dataclass(frozen=True, slots=True)
class CompiledTablePlan:
    cols: str
    emits: list[CompiledEmit]
    formatters: list[Callable[[Any], str] | None]


# ruff: noqa: PLR0915
def _compile_emitters(
    table: TableInspection,
    gen_plans: dict[tuple[str, str], GenerationPlan],
    plan_ctx: PlanContext,
) -> CompiledTablePlan:
    compiled: list[CompiledEmit] = []
    formatters: list[Callable[[Any], str] | None] = []
    append = compiled.append
    fmt_append = formatters.append

    cols = ", ".join(c.name for c in table.columns)

    for c in table.columns:
        gen_plan = gen_plans[(table.table, c.name)]
        planner = gen_plan.col_planner

        if hasattr(planner, "compile"):
            data_type, value_fn = planner.compile(  # type: ignore[attr-defined]
                c,
                gen_plan.suggestion,
                plan_ctx,
            )
            fmt = get_formatter(data_type)
            append(
                CompiledEmit(
                    name=c.name,
                    data_type=data_type,
                    value_fn=value_fn,
                    formatter=fmt,
                )
            )
            fmt_append(fmt)
            continue

        # Fallback: legacy planners (slower). Keep the column, but treat as STRING.
        def _make_value_fn(
            _planner: Any = planner,
            _col: Any = c,
            _sug: Any = gen_plan.suggestion,
            _ctx: Any = plan_ctx,
        ) -> Callable[[], Any | None]:
            def _value() -> Any | None:
                ed = _planner.plan(_col, _sug, _ctx)
                return None if ed is None else ed.value

            return _value

        append(
            CompiledEmit(
                name=c.name,
                data_type=SqlType.STRING,
                value_fn=_make_value_fn(),
                formatter=get_formatter(SqlType.STRING),
            )
        )
        fmt_append(get_formatter(SqlType.STRING))

    return CompiledTablePlan(cols=cols, emits=compiled, formatters=formatters)


def _write(out: TextIO | None, text: str) -> None:
    if out is None:
        print(text, end="")
    else:
        out.write(text)


def generate_data(  # NOSONAR(S3776)
    out_path: Path | None,
    app_ctx: AppContext,
    insp_ctx: InspectionContext,
    insp_res: list[TableInspection],
    gen_plans: dict[tuple[str, str], GenerationPlan],
) -> None:
    file_cm = out_path.open("w", buffering=1024 * 1024) if out_path is not None else nullcontext(None)

    with file_cm as out_handle:
        if out_handle is not None:
            out_handle.write(make_file_header(app_ctx.seed, str(insp_ctx.rows_per_table)))

        compiled_by_table: dict[str, CompiledTablePlan] = {
            t.table: _compile_emitters(t, gen_plans, insp_ctx.plan_context) for t in insp_res
        }

        batch_size = insp_ctx.insert_batch_size

        for t in insp_res:
            plan = compiled_by_table[t.table]
            fns = [e.value_fn for e in plan.emits]
            fmts = plan.formatters
            cols = plan.cols

            values: list[Any] = [None] * len(fns)

            if batch_size == 1:
                prefix = f"INSERT INTO {t.table} ({cols}) VALUES ("
                suffix = ");\n"

                for _ in range(insp_ctx.plan_context.rows_per_table):
                    for i, fn in enumerate(fns):
                        values[i] = fn()
                    vals = format_values_fast(values, fmts)
                    _write(out_handle, f"{prefix}{vals}{suffix}")

                continue

            prefix = f"INSERT INTO {t.table} ({cols}) VALUES\n"
            tuples: list[str] = []
            tuples_append = tuples.append

            def flush(_prefix: str = prefix, _tuples: list[str] = tuples) -> None:
                if not _tuples:
                    return
                stmt = _prefix + ",\n".join(_tuples) + ";\n"
                _write(out_handle, stmt)
                _tuples.clear()

            for row_idx in range(insp_ctx.plan_context.rows_per_table):
                for i, fn in enumerate(fns):
                    values[i] = fn()
                vals = format_values_fast(values, fmts)
                tuples_append(f"({vals})")

                if (row_idx + 1) % batch_size == 0:
                    flush()

            flush()
